services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  
      MYSQL_DATABASE: weather_db       
      MYSQL_USER: user                   
      MYSQL_PASSWORD: userpassword       
    ports:
      - "3306:3306"  
    volumes:
      - mysql-data:/var/lib/mysql 

  nestjs:
    build:
      context: ./ 
    container_name: nestjs-container
    depends_on:
      - mysql  
    ports:
      - "3000:3000" 
    environment:
      DB_HOST: mysql  
      DB_PORT: 3306 
      DB_USERNAME: use
      DB_PASSWORD: userpassword
      DB_DATABASE: weather_db  
    env_file:
      - .env

volumes:
  mysql-data:
