services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    env_file:
      - .env 
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  nestjs:
    build:
      context: ./
    container_name: nestjs-container
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    env_file:
      - .env

volumes:
  mysql-data:
